spring.application.name=InvenCore

# ===================================================================
# DATABASE (DataSource)
# ===================================================================
# ?????? ??? ?? URL, ??? ??, ????? ?????.
spring.datasource.url=jdbc:postgresql://43.202.51.25:5432/invencore
spring.datasource.username=invenmaster
spring.datasource.password=invencore123

# ===================================================================
# JPA / Hibernate
# ===================================================================
# ?????? ?? ? ???? ???? ???? ???? ???????. (????? ??)
spring.jpa.hibernate.ddl-auto=update
# ???? SQL ??? ??? ?????.
spring.jpa.show-sql=true
# SQL ??? ?? ?? ??????.
spring.jpa.properties.hibernate.format_sql=true