spring.application.name=InvenCore

spring.datasource.url=jdbc:postgresql://52.78.176.155:5432/invencore
spring.datasource.username=invenmaster
spring.datasource.password=invencore123

spring.jpa.properties.hibernate.default_schema=inven_schema
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
